### ISSUE TITLE
TUM data

### ISSUE THREAD

**Issue by jzhap** [BehnooshParsa/MTL-ERA#1]
May I request the TUM dataset which contains joints, labels and REBA_Score_Framewise? I have tried the Pose3D to extract the joints but the frame is not corresponding to the label provided in [https://github.com/BehnooshParsa/HumanActionRecognition_with_ErgonomicRisk](url)

**Comment by BehnooshParsa** [comment]
Hi,
Unfortunately, I don't have access to that data anymore. You can download TUM data from their website and follow the steps in the paper to get those artifacts. There might be a few extra frames that don't match with the labels and for that, you can trim from the end of the video. But this should be only 2-3 frames.

**Comment by jzhap** [comment]
> Hi, Unfortunately, I don't have access to that data anymore. You can download TUM data from their website and follow the steps in the paper to get those artifacts. There might be a few extra frames that don't match with the labels and for that, you can trim from the end of the video. But this should be only 2-3 frames.

Sure. Thank you!
